project:
  type: website
  output-dir: _site

website:
  title: "A Small Stage" 
  site-url: "https://YaraRin.github.io/my_blog"
  # 很有意思的改动，康德要是听到了估计会愣住一秒
  description: "小时候仰望星空，忘记了心中的道德律令了。"
  
  navbar:
    background: dark
    collapse: true
    left:
      - text: "Archive / 档案"
        href: index.qmd
      - text: "Gaming"
        href: "index.qmd#category=Gaming"
      - text: "Research"
        href: "index.qmd#category=Research"
      - text: "Story"
        href: "index.qmd#category=story"
    right:
      - text: "About"
        href: about.qmd
      - icon: envelope
        href: mailto:GreenwichintheSky@outlook.com

format:
  html:
    theme:
      light: cosmo  # 或者你现在用的主题名，比如 flatly, minimal 等
      dark: darkly # 官方推荐的暗色主题，或者用 vapor, slate
    # 这一行确保在导航栏显示切换图标
    dark-mode-switch: true
    page-layout: full
    hover-footnotes: true
    date-format: "YYYY-MM-DD"
    css: styles.css
    toc: true
    toc-title: "目录"
    code-fold: true
    code-summary: "展开查看代码"
    code-copy: true
    lightbox: true
    link-external-newwindow: true
    comments:
      giscus:
        repo: YaraRin/my_blog
        repo-id: R_kgDORxBgzw
        category: Comments
        category-id: DIC_kwDORxBgz84C5_8x
        mapping: pathname
        reactions-enabled: true
        theme: light
        language: zh-CN

# 博客列表页配置
listing:
  contents: posts
  type: grid           
  grid-columns: 3      
  image-height: 220px  
  grid-item-border: false 
  grid-item-align: left
  fields: [image, title, date, categories, description] 
  sort: "date desc"
  categories: true
  max-description-length: 50

# 语言设置
lang: zh

